import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton';
import { AppCard } from '@/components/AppCard';
import { Screen } from '@/components/Screen';
import { StatusBadge } from '@/components/StatusBadge';
import { useAuth } from '@/contexts/AuthContext';
import { useAppTheme } from '@/hooks/useAppTheme';
export default function AccueilScreen() { const { user } = useAuth(); const { colors, spacing } = useAppTheme(); return <Screen><Text style={[styles.eyebrow, { color: colors.primary }]}>GESTION DE FLOTTE</Text><Text style={[styles.title, { color: colors.text }]}>Bonjour, {user?.firstName}</Text><Text style={[styles.description, { color: colors.mutedText }]}>Voici l’état de votre flotte aujourd’hui.</Text><View style={styles.grid}>{[['3', 'Actifs'], ['1', 'Disponibles'], ['2', 'Alertes'], ['1', 'Entretiens']].map(([value, label]) => <View key={label} style={[styles.stat, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.value, { color: colors.text }]}>{value}</Text><Text style={[styles.label, { color: colors.mutedText }]}>{label}</Text></View>)}</View><AppCard><Text style={[styles.section, { color: colors.text }]}>Action rapide</Text><Text style={[styles.description, { color: colors.mutedText }]}>Enregistrez un plein ou signalez une anomalie.</Text><View style={{ height: spacing.md }} /><AppButton label="Enregistrer un plein" onPress={() => router.push('/actions/enregistrer-plein')} /><View style={{ height: spacing.sm }} /><AppButton label="Signaler une anomalie" variant="secondary" onPress={() => router.push('/actions/signaler-anomalie')} /></AppCard><View style={{ height: spacing.lg }} /><AppCard><Text style={[styles.section, { color: colors.text }]}>Renault Mégane</Text><Text style={[styles.description, { color: colors.mutedText }]}>FF-069-VC · 48 230 km</Text><View style={{ height: spacing.md }} /><StatusBadge status="En circulation" /><View style={{ height: spacing.md }} /><AppButton label="Voir le véhicule" variant="secondary" onPress={() => router.push({ pathname: '/vehicules/[id]', params: { id: 'renault-megane' } })} /></AppCard></Screen>; }
const styles = StyleSheet.create({ eyebrow: { fontSize: 12, fontWeight: '800', letterSpacing: 1.2, marginTop: 8 }, title: { fontSize: 28, fontWeight: '800', marginTop: 8 }, description: { fontSize: 14, lineHeight: 21, marginTop: 6 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginVertical: 20 }, stat: { borderRadius: 16, borderWidth: 1, minWidth: '47%', padding: 16 }, value: { fontSize: 26, fontWeight: '800' }, label: { fontSize: 13, marginTop: 4 }, section: { fontSize: 18, fontWeight: '800' } });
