import { router, useLocalSearchParams } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton';
import { AppCard } from '@/components/AppCard';
import { Screen } from '@/components/Screen';
import { StatusBadge } from '@/components/StatusBadge';
import { useAppTheme } from '@/hooks/useAppTheme';
const data: Record<string, { name: string; plate: string; mileage: string; status: 'Disponible' | 'En circulation' | 'En entretien' | 'Immobilisé' }> = { 'renault-megane': { name: 'Renault Mégane', plate: 'FF-069-VC', mileage: '48 230 km', status: 'En circulation' }, 'fiat-panda': { name: 'Fiat Panda', plate: 'GQ-639-LB', mileage: '31 805 km', status: 'En circulation' }, 'toyota-aygo': { name: 'Toyota Aygo', plate: 'FK-868-VS', mileage: '18 420 km', status: 'Disponible' } };
export default function VehiculeDetailScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const vehicle = data[id || 'renault-megane'] || data['renault-megane']; const { colors, spacing } = useAppTheme(); return <Screen><Text style={[styles.title, { color: colors.text }]}>{vehicle.name}</Text><Text style={[styles.detail, { color: colors.mutedText }]}>{vehicle.plate} · {vehicle.mileage}</Text><View style={{ marginVertical: spacing.lg }}><StatusBadge status={vehicle.status} /></View><AppCard><Text style={[styles.section, { color: colors.text }]}>Résumé</Text><Text style={[styles.detail, { color: colors.mutedText }]}>Dernier plein : 02/10/2026 · 42,6 L</Text><Text style={[styles.detail, { color: colors.mutedText }]}>Consommation moyenne : 6,8 L/100 km</Text><Text style={[styles.detail, { color: colors.mutedText }]}>Prochain entretien : 15/11/2026</Text></AppCard><View style={{ height: spacing.lg }} /><AppButton label="Enregistrer un plein" onPress={() => router.push('/actions/enregistrer-plein')} /><View style={{ height: spacing.sm }} /><AppButton label="Signaler une anomalie" variant="secondary" onPress={() => router.push('/actions/signaler-anomalie')} /></Screen>; }
const styles = StyleSheet.create({ title: { fontSize: 28, fontWeight: '800', marginTop: 8 }, detail: { fontSize: 14, lineHeight: 22, marginTop: 6 }, section: { fontSize: 18, fontWeight: '800' } });
